#!/bin/bash
python src/npsl.py --verbose --in-file=src/main.npsl --client --out-folder=tmp/python_client --out-language=python 
python src/npsl.py --verbose --in-file=src/main.npsl --server --out-folder=tmp/python_server --out-language=python