#!/bin/bash
python src/npsl.py --verbose --in-file=examples/mediaplayer.npsl --client --out-folder=tmp/python_mediaplayer_client --out-language=python 
python src/npsl.py --verbose --in-file=examples/mediaplayer.npsl --server --out-folder=tmp/python_mediaplayer_server --out-language=python